### PR TITLE
Travis-CI to Github Actions

### LINKED ISSUE #211: Travis-CI to GitHub Actions
Old Travis-CI.org service will be shut down after 31th of December, requiring either action to migrate to the commercial Travis-CI.com service or migrating to a new CI altogether. [An rOpenSci blogpost](https://ropensci.org/technotes/2020/11/19/moving-away-travis/) describes the pros of moving to GitHub Actions. The process is as follows:

1. run: `usethis::use_github_action_check_standard()`
2. Check if package tests contain skip_on_travis -functions and replace them with skip_on_ci 
3. Add a badge to the package README: `[R build status](https://github.com/rOpenGov/PACKAGENAME/actions)`
4. Remove Travis CI badge (and Appveyor badge as well, since GHA runs tests simultaneously for Linux, macOS and Windows)

### PR DESCRIPTION
**Pull request by pitkant**
Change CI platform from Travis to GitHub Actions, as described in the linked issue

Close #211

### CODE REVIEW

**Comment by MansMeg** [comment]
This looks good, but there is a test that fails. Can you check:
```FAILURE (test-pxweb_get.R:65:5): Previous bugs``` ? to see what the error is?

**Comment by antagomir** [comment]
Seems to be this one
```

test_that(desc="Previous bugs",{
  # CRAN seem to run tests in parallel, hence API tests cannot be run on CRAN.
  skip_on_cran()
  
  # This is a bug in the previous implementation of pxweb
  url <- "http://bank.stat.gl/api/v1/en/Greenland/BE/BE01"
  tryr <- try(httr::GET(url), silent = TRUE)
  if(!inherits(tryr, "try-error")){
    expect_silent(px_meta_data <- pxweb_get(url))
    expect_output(print(px_meta_data), regexp = "PXWEB LEVELS")
  }

})  
```

**Comment by pitkant** [comment]
The test seems to have failed because pxweb url has changed from  http://bank.stat.gl/api/v1/en/Greenland/BE/BE01 to https://bank.stat.gl/api/v1/en/Greenland/BE/BE01, which produced the following warning message, making the test fail since it was not silent:
```
PXWEB URL CHANGE:
 from: http://bank.stat.gl/api/v1/en/Greenland/BE/BE01
 to:   https://bank.stat.gl/api/v1/en/Greenland/BE/BE01
```
I can push a fix to this since it seems the purpose of this test was not to replicate bugs... or was it? Maybe expect_warning would be more appropriate?

**Comment by MansMeg** [comment]
Ah, yes. Just fix that and I think we are all home.

**Comment by pitkant** [comment]
I guess Appveyor checks can be disabled by removing Appveyor (and Travis CI) web hooks from Settings - Webhooks. They do not function as I removed the .yml files

**Comment by MansMeg** [comment]
Yes. Now fixed! Great work!

**Pull request merged**
