### PR TITLE
Adding code from package PxWebApiData

### PR DESCRIPTION
**Pull request by olangsrud**
Adding code results in Warning message: replacing previous import ‘RJSONIO::toJSON’ by ‘jsonlite::toJSON’ when loading ‘pxweb’

### CODE REVIEW

**Comment by MansMeg** [comment]
Ok. Hmmm could you merge this into a branch (maybe called PxWebApiData) so we can solve this before we merge into the master branch. I want the master to be stable and pass on Travis.

/Måns

**Comment by olangsrud** [comment]
Close this and I will try to make a branch

**Comment by olangsrud** [comment]
I am not so familiar with branches at GitHub. I tried to make a new branch at my forked repository. But when making a pull request it seems that I anyway have to select an existing branch at rOpenGov/pxweb. Maybe someone could create the branch first? Or maybe I should be allowed to create it?

**Comment by MansMeg** [comment]
Sure! I make you a collaborater. Then you can clone, add it in branch, push and then we merge.

**Pull request closed without merging**
