### PR TITLE
Added Nordic Statistics Database to API list.

### PR DESCRIPTION
**Pull request by emilwest**
Under citation I omitted the adress-field, but one could possibly write 'The Nordic Region' here if it is mandatory to include it.

### CODE REVIEW

**Comment by MansMeg** [comment]
Thanks! Running tests now.

**Comment by MansMeg** [comment]
Great that you fixed this. Rerunning tests.

**Comment by MansMeg** [comment]
Ok. Something is strange. Ill fix.

**Comment by emilwest** [comment]
Thanks!

**Pull request merged**
