### PR TITLE
add Statistics Switzerland

### PR DESCRIPTION
**Pull request by t0b3**

### CODE REVIEW

**Comment by MansMeg** [comment]
The statistics netherland api address is incorrect? I cant find anything on their homepage. Maybe they have not enabled the api.

**Comment by t0b3** [comment]
> The statistics netherland api address is incorrect? I cant find anything on their homepage. Maybe they have not enabled the api.

This PR was in fact about Switzerland not Netherland.
Any reason for dropping Switzerland in [this very commit](https://github.com/rOpenGov/pxweb/commit/a507b3813d7f0918c08a5e93aa40e6a0ef23b2b6)?

Could you add Switzerland again, this would be very helpful for us here... Thx

**Comment by MansMeg** [comment]
Sorry. I meant Switzerland. Yes I dropped it since this is the pxweb webpage, not the api. They need to enable the api for the package to work. The easiest is to just send them an e-mail and ask. It is very simple to enable the api for them.

**Comment by antagomir** [comment]
Even if the API is not open, the pxweb R pkg could be useful for those who have access to the closed API. Then, it could be useful to keep the closed API addresses in the pkg somehow.

**Comment by MansMeg** [comment]
? What is a closed api? Never herd about it for pxweb?

**Comment by MansMeg** [comment]
I think you can have pxweb without the api active (just to get data interactively in the browser). The owner the pxweb site can simply turn the api on, but it is not on by default.

**Comment by t0b3** [comment]
@MansMeg I thought the API to be working as fine as any other api
[demo_pxweb_api_switzerland.txt](https://github.com/rOpenGov/pxweb/files/2511873/demo_pxweb_api_switzerland.txt)
What do you mean Switzerland could improve to meet your expectations of a working api?

**Comment by MansMeg** [comment]
Yes. Now it worked? I must have done something strange. Now its in the master branch. Thanks!

**Comment by t0b3** [comment]
Great! Thank you very much.

**Pull request closed without merging**
