### PR TITLE
Add Statistics Estonia

### PR DESCRIPTION
**Pull request by jussuf**
This is official PxWeb API for Statistics Estonia. Please include in API catalogue.

### CODE REVIEW

**Comment by MansMeg** [comment]
Great! I'll just let the tests run before merging. Thanks!

**Comment by pitkant** [comment]
Since this is a simple addition to the API.json I'm sure that these tests (now with GitHub Actions instead of Travis and Appveyor) would undoubtedly pass but maybe it's worth a shot to run those tests again.

@MansMeg @jussuf

**Comment by MansMeg** [comment]
Yes. Or if we just add this in your other PR. Then we could close this one.

**Comment by MansMeg** [comment]
Now in the API catalogue through the other PR.

**Pull request closed without merging**
