### PR TITLE
An encoding argument for get_pxweb_data.

### LINKED ISSUE #146: Encoding argument to content
I am having encoding problems with 

``` 
dat <- 
  get_pxweb_data(url = "http://pxnet2.stat.fi/PXWeb/api/v1/fi/StatFin/tym/tyonv/statfin_tyonv_pxt_001.px",
                 dims = list(Kuukausi = c('2006M01'),
                             Alue2018 = c('005'),
                             Muuttujat = c('TYOTTOMAT')),
                 clean = TRUE)
```

The problem is probably on statfi side, but I can overdrive it with setting a encoding for `httr::content()`. So it would be nice to be able to set the content encoding in `get_pxweb_data()`.

That would require only to chance:
```
get_pxweb_data <- function(url, dims, clean = FALSE, encoding = NULL) 
```
and row 80:
```
suppressMessages(a <- httr::content(response, as="text", encoding = encoding))
```

### PR DESCRIPTION
**Pull request by jhuovari**
Fixes #146

### CODE REVIEW

**Comment by MansMeg** [comment]
Hmmm. Seem to be some problem with the runs. It is not related to the submission, though. Ill look into this

**Comment by MansMeg** [comment]
Closed and opened to trigger CI.

**Comment by MansMeg** [comment]
It is now merged to the development branch. I'll push it to the test branch and then you can install it from the test branch. Or do you want me to bump it to the master? Maybe that would be easier.

**Comment by jhuovari** [comment]
Nice, thanks. I don't have an urgent need for it now, so no hurries.

**Pull request merged**
