### PR TITLE
Antagomir

### LINKED ISSUE #122: visitfinland to be added into API catalog
Received request to add http://visitfinland.stat.fi/PXWeb/pxweb/fi/VisitFinland to pxweb api catalog.

### PR DESCRIPTION
**Pull request by antagomir**
Visit Finland catalog now added. Fixes #122

### CODE REVIEW

**Comment by MansMeg** [comment]
Hi!
Great job! 

I have tests that care about the order in the api catalogue. Hence this addition fail:
  OK: 522 SKIPPED: 14 FAILED: 3
  1. Failure: API catalogue usage (@test-pxweb_interactive.R#54) 
  2. Failure: Stat Iceland structure (@test-pxweb_interactive.R#120) 
  3. Failure: Stat Iceland structure (@test-pxweb_interactive.R#122) 

I also just submitted a v0.9.1 to CRAN so the version number is also incorrect. It would be good if you could either fix this (ie put the visit finland last in the api catlogue or fix the test suites) or PR to the development branch where we can clean this up.

**Comment by MansMeg** [comment]
Also, Visit Finland seem to be connected to Buisness Finland rather than Statistics Finland (for citation purposes).

**Comment by antagomir** [comment]
Will do. Business Finland has ordered this Statistics Finland has implemented it and provides the service. Perhaps any of these two can be cited.

**Comment by MansMeg** [comment]
I actually do not know which one to cite correctly. My guess is that it should be the publisher?

**Comment by antagomir** [comment]
Ok I will switch to development.

**Comment by antagomir** [comment]
How about "Business Finland / Statistics Finland" so both will be mentioned? Or I can ask them by email what they prefer. They already stated to me (from Visit Finland / Business Finland) that the service is provided by Statistics Finland.

**Comment by MansMeg** [comment]
I think we should probably check with a librarian what would be the correct. I'll check with Jan, he should know this. @janbrus, do you know how citing data should be done in this situation?

**Pull request closed without merging**
