### PR TITLE
Fix missing pages on gh deployment

### LINKED ISSUE #245: rog template is failing on github actions
See:
https://github.com/rOpenGov/pxweb/actions/runs/2597167204

I don't really know how this works.

### PR DESCRIPTION
**Pull request by dieghernan**
Fix #245 

Issue was that some additional packages (`devtools`?) was added on the article. While this is not a problem when checking the package (articles are ignored, vignettes are not), but when running `pkgdown` all needed packages needs to be installed.

Packages needed on vignettes are declared on DESCRIPTION, while articles can have additional packages (I often do this), but then it is neccesary to ensure that the GH action also installs the packages needed on the articles.

Hope this make sense, regards

### CODE REVIEW

**Comment by pitkant** [comment]
Looks like we were working simultaneously on the same issue :D Your solution is generally speaking the correct way to declare needed packages, especially in the case of articles, but here it was about an actual vignette... remotes was also already listed in Suggests whereas devtools was not so to me the simplest solution was to change the vignette example to use remotes instead of devtools, since remotes is anyway the preferred way to install development versions from Github, at least [according to some users](https://twitter.com/bearloga/status/1235985861944184832).

What I found a bit puzzling was that pkgdown seemed to require devtools even if the code chunk in question was `eval = FALSE`, why is that?

**Comment by dieghernan** [comment]
> What I found a bit puzzling was that pkgdown seemed to require devtools even if the code chunk in question was eval = FALSE, why is that?

Honestly I don’t know, it is weird indeed

**Comment by MansMeg** [comment]
This is great! Can you decide on which PR to merge? =)

**Comment by dieghernan** [comment]
I leverage here on @pitkant decision.

**Comment by MansMeg** [comment]
Ok. Could you set that up so I can merge?

**Pull request merged**
